### ISSUE TITLE
Lidar sensor's ray angles are fixed relative to world frame, but not to Agent frame

### ISSUE THREAD

**Issue by wt160** [proroklab/VectorizedMultiAgentSimulator#100]
In the current implementation, even the Agent's angle could be changed, but the sensor Lidar's ray angles are fixed relative to the world frame, which is not obvious when the lidar has 360 fov. 
Since the lidar supports different fovs, it seems the current configuration is kind of anti-intuition.

**Comment by matteobettini** [comment]
Thanks a lot for this, I'll fix it right away

**Comment by matteobettini** [comment]
Let me know if the PR works for you
