### ISSUE TITLE
Feature  request: Bool for rendering sensors

### ISSUE THREAD

**Issue by Zartris** [proroklab/VectorizedMultiAgentSimulator#107]
Hi 

A small request for having a bool for disabling sensor rendering, just like the _render_action option.
I would love to manually render the sensors on the ego agent, but not everyone as with lidar that can get out of hand.

core.py around line 1050

thanks.

**Comment by matteobettini** [comment]
does #108 do what you need?

**Comment by Zartris** [comment]
Yes and no, I can make it work with this, but then I have to overwrite a private variable ( the _render on the sensor)

I want to, by default, not render any sensors, but then in the extra_render method of my environment to do the following:

    def extra_render(self, env_index: int = 0) -> "List[Geom]":
        geoms: List[Geom] = []

        # ego agent
        obs_agent = self.world.agents[0]

        # render lidar
        if self.config.get("use_lidar", False):
            lidar = obs_agent.sensors[0]
            geoms += lidar.render(env_index)

but that is not possible without going:
lidar._render = True and then toggle this every time I either change the ego agent or on every extra_render call

**Comment by matteobettini** [comment]
I am not sure I get why the solution does not work.

Essentially in #108 you can decide weather a lidar will be rendering at construction time `Lidar(render=False)`.

If you want to change the lidar rendering property dynamically, you can to `lidar.set_render(True)`

I do not think you should be rendering lidars in `extra_render`, they should be handled automatically as part of the agent rendering

**Comment by matteobettini** [comment]
In your case i would do:

```pyhton
def make_world()
    use_lidar=True
    agent = Agent(sensors=[Lidar()] if use_lidar else [])
```
so I am not even sure you need to disable lidars rendering as you can just avoid adding a lidar in the first place

**Comment by Zartris** [comment]
You are right that I could use the set_render, I missed that you also included this function and did only see the field in init.
I am not sure where you got that I am gathering observations in the extra_render. I am just visualising one agents lidar because showing all of them gets too much.
Bu yes your solution will work for me 👍
