### ISSUE TITLE
Weld joint/constraint

### ISSUE THREAD

**Issue by rikifunt** [proroklab/VectorizedMultiAgentSimulator#109]
Hi,

is there any way to add a "weld" constraint/joint between two entities (remove all relative degrees of freedom)? I tried starting from the joint_passage scenarios with no luck (my use case is implementing agents "grabbing" objects to push them around).

If this is not currently possible, are there any plans to implement something like this in the future?

Thanks

**Comment by matteobettini** [comment]
Hello,

Have you looked at the join constraints?https://github.com/proroklab/VectorizedMultiAgentSimulator/blob/479db49a179718c063732f80d05aa94a72fd5ce1/vmas/simulator/joints.py#L21-L32

You can definitely have a joint at distance 0 with rotations in the ancors disabled

**Comment by rikifunt** [comment]
Thank you for the quick response. Yes, I tried disabling `rotate_a` and `rotate_b`, and while this does constrain relative position correctly, it does not seem to constrain relative rotation. Here is a quick demo (agent is blue, black box is a landmark):

![test_scratch_small](https://github.com/proroklab/VectorizedMultiAgentSimulator/assets/15875311/772d43ab-98e8-45bb-993f-995c74b67d10)

as you can see at the end, the rotation of the agent is independent from that of the black box. What I would like to do is also constrain the relative rotation between the agent and the box, so that the agent rotating also causes the whole agent-box system to rotate (as if they were a single entity). Is this currently possible? Am I missing something else?

I am using the following code to create the joint:
```python
self.joint = Joint(
    self.agent,
    self.mass,
    anchor_a=(0, 0),
    anchor_b=(0, 0),
    dist=0.12,
    rotate_a=False,
    rotate_b=False,
    collidable=False,
    width=0,
    mass=1,
)
world.add_joint(self.joint)
```

**Comment by rikifunt** [comment]
Yes, this is exactly what I had in mind! (and more). I have tested several configurations (with >2 linked bodies and >=2 linked agents), and everything seemed to work as I expected. Thank you!
