### ISSUE TITLE
Inconsistency with shared reward args name 

### ISSUE THREAD

**Issue by KaleabTessera** [proroklab/VectorizedMultiAgentSimulator#114]
In some places the shared reward param is called `share_reward` (e.g. https://github.com/proroklab/VectorizedMultiAgentSimulator/blob/f4f8a8964336a86e60bc06ae72b51a2ae0a1e4af/vmas/scenarios/dispersion.py#L16), while in others `shared_rew` (e.g. 
https://github.com/proroklab/VectorizedMultiAgentSimulator/blob/f4f8a8964336a86e60bc06ae72b51a2ae0a1e4af/vmas/scenarios/multi_give_way.py#L28C39-L28C49). 

Since there is no validation on the kwargs, it is easy to make a mistake with the name of this param, especially since it is not consistent. I think making all envs have the same param name would be useful.

**Comment by matteobettini** [comment]
Hey!

Yes, I feel the same way.

For backwards compatibility reasons I cannot change the names now as this would cause all sorts of issues, what I can do is adding kwargs checking so that if users pass a parameter that is not expected we raise an error

What do you think?

**Comment by KaleabTessera** [comment]
Yeah sounds good. I like your implementation :+1:
