### ISSUE TITLE
[DISCOVERY] Duplicate value in observation function 

### ISSUE THREAD

**Issue by Giovannibriglia** [proroklab/VectorizedMultiAgentSimulator#131]
Issue:
- In the discovery scenario, I noticed that in the observation function, at this line https://github.com/proroklab/VectorizedMultiAgentSimulator/blob/ee892d8143a576c4d6a435c33d27dfd9b1a974de/vmas/scenarios/discovery.py#L236 , the agent.state.pos is included twice in the observation array.

Question:

- What is the intended purpose of including agent.state.pos twice in the observation? Is this behavior correct?

Suggestion:
  - Could the comment part at this line https://github.com/proroklab/VectorizedMultiAgentSimulator/blob/ee892d8143a576c4d6a435c33d27dfd9b1a974de/vmas/scenarios/discovery.py#L238 be used to replace the duplicate?

Thank you :)

**Comment by matteobettini** [comment]
Will remove the duplicate. Lidar 2 was removed as we don't allow to see other agents (need to communicate) but will put a kward to have it back
