### ISSUE TITLE
Visualizing boundaries in dimension-limited environments

### ISSUE THREAD

**Issue by Giovannibriglia** [proroklab/VectorizedMultiAgentSimulator#134]
**Issue:**
In certain scenarios, users may work with environments that have limited dimensions, which can be configured using the "x_semidim" and "y_semidim" parameters. In such cases, it would be beneficial to visualize these boundaries in the rendering output.

**Questions:**
- Are there specific environments where visualizing these boundaries could cause issues?
- Is it possible to display the configured boundaries in rendering mode?

**Suggestion:** I noticed that you've already implemented the following objects:
- rendering: from vmas.simulator import rendering
- Line: from vmas.simulator.rendering import Line
- Color: from vmas.simulator.utils import Color

These could be utilized to display the environment boundaries effectively.

**Comment by matteobettini** [comment]
Very cool and needed

**Comment by matteobettini** [comment]
I am open to have this, we just need to figure out how to deal with agents of different sizes as the boundaries would be on their center.
 
Recapping, we could:

1. render the boundaries as they are, meaning that all agents are able to go half their radius on top of them
2. rendering at them for the maximum radious, meaning that smaller agents will seem not to touche them

I am more for 1 but open to discuss

**Comment by matteobettini** [comment]
> Could there be any potential user issues or disapproval with this visualization? Does it still seem intuitive and clear?

the issue here is that if you want to use the boundary as something to crop the rendering you can't as half of your agent will be outside it. but it still seems the best option for me

> An implementation problem arises for scenarios where the variables 'x_semidim' and 'y_semidim' are named differently.

What do you mean? `world.x_semidim` is always the same and the one we should use

**Comment by matteobettini** [comment]
The implementation can go as follows

1. in `Scenario` we have an attribute `visualize_semidims` defaulting to true
2. in render, if we have this attribute we call a function to plot the boundaries
3. the function checks what semidims are not None and 
    -  if both are not None, plot a square
    - if only one is not None plot ultra long parallel lines in that direction

I suggest we use a gray with an alpha a bit less than 1 for the plotting to not be invasive

**Comment by Giovannibriglia** [comment]
> > Could there be any potential user issues or disapproval with this visualization? Does it still seem intuitive and clear?
> 
> the issue here is that if you want to use the boundary as something to crop the rendering you can't as half of your agent will be outside it. but it still seems the best option for me
> 
> > An implementation problem arises for scenarios where the variables 'x_semidim' and 'y_semidim' are named differently.
> 
> What do you mean? `world.x_semidim` is always the same and the one we should use

Yes, that's true!! Perfect.
