### ISSUE TITLE
MPE - Simple Reference Reward Question

### ISSUE THREAD

**Issue by fourpenny** [proroklab/VectorizedMultiAgentSimulator#149]
The reward function for agents in the VMAS version of the Simple Reference scenario from the MPE differs from the current implementation in Petting Zoo. 

Petting Zoo either [penalizes individual agents for their distance from their corresponding landmark](https://github.com/Farama-Foundation/PettingZoo/blob/master/pettingzoo/mpe/simple_reference/simple_reference.py#L153) or [returns an average of these penalties across all agents](https://github.com/Farama-Foundation/PettingZoo/blob/master/pettingzoo/mpe/simple_reference/simple_reference.py#L162).

In VMAS, the reward is calculated only [based on the position of the first agent in the environment's distance from landmarks](https://github.com/proroklab/VectorizedMultiAgentSimulator/blob/main/vmas/scenarios/mpe/simple_reference.py#L110).

Is this difference intentional? It seems like this implementation would make it difficult for both agents to learn to approach their corresponding landmark.

**Comment by matteobettini** [comment]
Hello,

Have you read this?
https://github.com/proroklab/VectorizedMultiAgentSimulator/issues/62#issuecomment-1781214094

It should have the answer

Vmas follows the logic of the original MPE repository while PettingZoo changed a few things

also i think you misunderstood the vmas code: We are not using the position of the first agent only, we are just computing the reward on the first call of the function

**Comment by fourpenny** [comment]
Thanks for the link to the previous issue - sorry for missing it! I also see that on line 114 the function later references all agents as you mentioned. I will try out some of the strategies you suggested and hopefully get some better performance in my own training now that I have a better understanding of the reward calculation.

I appreciate your response and all the work on the VMAS library! It has been very useful to me so far while moving from primarily using rllib to trying out torchRL.

**Comment by matteobettini** [comment]
No problem, feel free to ask for further clarifications!
