### ISSUE TITLE
A pain to install on windows

### ISSUE THREAD

**Issue by Zartris** [proroklab/VectorizedMultiAgentSimulator#28]
Hi just want to add that this is hard to install on windows because of the ray[rllib].
They are still in beta on windows so you will most likely get the: 
`**ERROR: Could not find a version that satisfies the requirement ray (from versions: none)
ERROR: No matching distribution found for ray**`
and if you try to read their documentation, you are stuck with ray 3.0 which is not supported by this library.

Can you maybe extend the install section a bit? 
So if you have a solution for this, add that to the section or write that you only support Linux / macOS.
Or maybe we can update the requirements for this to support Ray 3.0?
Or having a branch without the support of RLLIB?

Im just coming up with suggestions :)

**Comment by matteobettini** [comment]
I will try to look into this and make ray an optional dependency.

Regarding the documentation, you can select the documentation version in the bottom right of the page https://docs.ray.io/en/latest/rllib/index.html

Ray 3.0 is not out yet, you are referring to the master branch.

**Comment by matteobettini** [comment]
Rllib is now an optional dependency in the latest release 1.2.0

https://github.com/proroklab/VectorizedMultiAgentSimulator/releases/tag/VMAS-1.2.0

also available through
`pip install vmas`

**Comment by Zartris** [comment]
Thank you for the quick change, it helped me out a lot :)
Secondly seems like you are missing the dependency of the package "six".
It is used in vmas>simulator>rendering.py

**Comment by matteobettini** [comment]
Six is a dependency now fdfe33d
