### ISSUE TITLE
Font file not in package

### ISSUE THREAD

**Issue by Zartris** [proroklab/VectorizedMultiAgentSimulator#30]
Hi again 

You have a reference in rendering.py to a font file that is not included.
 `pyglet.font.add_file(os.path.join(os.path.dirname(__file__), "secrcode.ttf"))`
So we cannot test the transport.py scenario.

**Comment by Zartris** [comment]
> Traceback (most recent call last):
  File "E:\code\python\Multi-Agent-Decision-Making\Environments\Airport.py", line 345, in <module>
    render_interactively(
  File "C:\Users\jfs\Anaconda3\envs\madm\lib\site-packages\vmas\interactive_rendering.py", line 277, in render_interactively
    InteractiveEnv(
  File "C:\Users\jfs\Anaconda3\envs\madm\lib\site-packages\vmas\interactive_rendering.py", line 68, in __init__
    self._init_text()
  File "C:\Users\jfs\Anaconda3\envs\madm\lib\site-packages\vmas\interactive_rendering.py", line 145, in _init_text
    text_line = rendering.TextLine(
  File "C:\Users\jfs\Anaconda3\envs\madm\lib\site-packages\vmas\simulator\rendering.py", line 305, in __init__
    pyglet.font.add_file(os.path.join(os.path.dirname(__file__), "secrcode.ttf"))
  File "C:\Users\jfs\Anaconda3\envs\madm\lib\site-packages\pyglet\font\__init__.py", line 183, in add_file
    font = open(font, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jfs\\Anaconda3\\envs\\madm\\lib\\site-packages\\vmas\\simulator\\secrcode.ttf'


I see that it is in the master, but when installing through pip I get this.

**Comment by UsaidPro** [comment]
I installed the latest VMAS version (1.2.3) through `pip install vmas` and got a similar error running a copy-paste of the [mpe/simple.py code:](https://github.com/proroklab/VectorizedMultiAgentSimulator/blob/main/vmas/scenarios/mpe/simple.py)
`FileNotFoundError: [Errno 2] No such file or directory: '/home/usaidm/.pyenv/versions/ml/lib/python3.8/site-packages/vmas/simulator/secrcode.ttf'`
Looking at the `site-packages` directory, here is what I see:
![image](https://user-images.githubusercontent.com/7944753/213083983-b43c8e52-f77a-4753-a0de-f9b8ea638210.png)

**Comment by matteobettini** [comment]
Thanks for posting this.

i have no idea why this happens as if you download the package directly from pypi the file is there
https://pypi.org/project/vmas/1.2.3/#files

I will try to dig deeper and try to install it from scratch on linux and see.

if you have an idea for a solution let me know

**Comment by matteobettini** [comment]
Ok.

Try again with `pip install vmas==1.2.4` and let me know. 

Should be fixed

**Comment by UsaidPro** [comment]
Updated to `vmas==1.2.6` and it works now, thanks! This issue can be closed again.
