### ISSUE TITLE
World actions or post step function

### ISSUE THREAD

**Issue by Zartris** [proroklab/VectorizedMultiAgentSimulator#32]
Hi, 

I want to make an entity disappear when entering a box. 
Not sure where to put this logic as it is a post-step action, but I'm not sure I should start extending the world as it handles mostly physics.

context: Lets say that when a package entity enters a box, a human is removing it from the system or a human is introducing a new package in the system (you could call it world-actions or environmental actions as it is not something any of our agents can control).
What I think could be the options:
1. Make an extension of the World class, adding this into the world.stop()
2. Extend the Environment class with a `self.scenario.post_step()` after the `self.world.step()` and let the scenario class handle the world action logic.
3. Having it as an action_script for the entity, but I want it to be processed after all actions are done.

Question is, where do you think this world-action logic should be applied?

**Comment by matteobettini** [comment]
So for post-step functions, you can use the `reward` function and do something like
```
is_last = agent == self.world.agents[-1]
if is_last:
      # code that is run after step
```
at the end of the function. In general, you are not supposed to touch the core or the BaseScenarios class. You should be able to do everything in your scenario file.

The `discovery` scenario provides an example of a scenario where entities have to be respawned or disappear. This can be tricky to do so make sure to familiarise yourself with it.
