### ISSUE TITLE
I strongly recommend that you should check your code!!!!!

### ISSUE THREAD

**Issue by wuzh77** [proroklab/VectorizedMultiAgentSimulator#33]
The same algorithm in the same environment, discrete action and continuous action final difference is very big. I strongly recommend that you have a good check.

**Comment by matteobettini** [comment]
Hello,

I would love to check the code and find new bugs, but I can only address issues that present a detailed, systematic and helpful description. 

If you could provide a through description of the issue, I could help you,

**Comment by wuzh77** [comment]
The environment I use is: wheel, two agents and num_ envs=1。

In the above environment, the algorithm I use is IPPO. I conducted two experiments only with different action spaces (discrete/continuous).

After running all the training times under the discrete action, you can't reach reward=-9.10. But after running 300 epochs in a row, the result is much better than the former.

**Comment by wuzh77** [comment]
Besides, I think you should explain the set parameters and the calculation method of rewards. My teacher asks me to realize all algorithms in your paper.

**Comment by wuzh77** [comment]
If you want to communicate in detail, my email is 1742272207@qq.com

**Comment by matteobettini** [comment]
Regarding the discrete/continuous actions performance discrepancy:

I think that is normal and expected especially in environments like wheel where robots have to move in a circular trajectory and that is way harder when their actions can only be moving horizontally and vertically.

Regarding the scenario parameters and the reward functions:

All the reward functions are in the code of each scenario under the `reward` function. To understand them you just have to understand the code. Same for the parameters.

**Comment by wuzh77** [comment]
I have a question about balance: in balance, if done=True is returned in an environment, do you want to continue counting the rewards of the actions after that?






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "proroklab/VectorizedMultiAgentSimulator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月18日(星期天) 凌晨0:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [proroklab/VectorizedMultiAgentSimulator] I strongly recommend that you should check your code!!!!! (Issue #33)





 
Regarding the discrete/continuous actions performance discrepancy:
 
I think that is normal and expected especially in environments like wheel where robots have to move in a circular trajectory and that is way harder when their actions can only be moving horizontally and vertically.
 
Regarding the scenario parameters and the reward functions:
 
All the reward functions are in the code of each scenario under the reward function. To understand them you just have to understand the code. Same for the parameters.

**Comment by wuzh77** [comment]
The rewards I mention is the&nbsp;Y-axis&nbsp;variable. I just want to know the way you count rewards in your paper.&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "proroklab/VectorizedMultiAgentSimulator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月18日(星期天) 凌晨0:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [proroklab/VectorizedMultiAgentSimulator] I strongly recommend that you should check your code!!!!! (Issue #33)





 
Regarding the discrete/continuous actions performance discrepancy:
 
I think that is normal and expected especially in environments like wheel where robots have to move in a circular trajectory and that is way harder when their actions can only be moving horizontally and vertically.
 
Regarding the scenario parameters and the reward functions:
 
All the reward functions are in the code of each scenario under the reward function. To understand them you just have to understand the code. Same for the parameters.

**Comment by wuzh77** [comment]
I need to realize the algorithms and effect on your paper. I want to know the way you count rewards in balance.

**Comment by matteobettini** [comment]
The "episode reward mean" in the paper is the sum of the rewards returned by the environment up until `done=True`. To get a single value we average over the agents (in case of global rewards this leaves everything unchanged). The "mean" in "episode reward mean" referes to a mean over the batch of training episodes.

**Comment by matteobettini** [comment]
> I have a question about balance: in balance, if done=True is returned in an environment, do you want to continue counting the rewards of the actions after that?

No
