### ISSUE TITLE
GPU resource distribution 

### ISSUE THREAD

**Issue by Berten15** [proroklab/VectorizedMultiAgentSimulator#38]
Hello I'm working with your framework for my Master's Dissertation, nice work!

But I don't understand how the distribution of GPU-resources happens.

```Python
RLLIB_NUM_GPUS = int(os.environ.get("RLLIB_NUM_GPUS", "0"))
    num_gpus = 0.001 if RLLIB_NUM_GPUS > 0 else 0  # Driver GPU
    num_gpus_per_worker = (
        (RLLIB_NUM_GPUS - num_gpus) / (num_workers + 1) if vmas_device == "cuda" else 0
    )
```
For example if I have 2 GPU's and 1 worker the Tune config will look like this:

```Python
config = {
...
    "num_gpus": 0.001,
    "num_gpus_per_worker": 0.9995 ,
...
}
```

And the Tune System info shows:
Resources requested:  1.0005/2 GPUs

Thank you for your time

**Comment by matteobettini** [comment]
So this is purely an rllib configuration so I sugget you reed their docs to understand this.
https://docs.ray.io/en/latest/rllib/rllib-training.html#specifying-resources

But basically "num_gpus" are the gpus assigned to the training process (here any number 0<num_gpus<=1 will assign one gpu to it). "num_gpus_per worker" is the number of gous per each worker collecting experience. again fractional numbers will round up to their ceil
