### ISSUE TITLE
Memory usage growing issue

### ISSUE THREAD

**Issue by wt160** [proroklab/VectorizedMultiAgentSimulator#42]
When I try out the scenario file or run the use_vmas_env script, I find my computer freeze after some time. Then I track the memory usage of the script, found that the memory usage keeps rising, for example, when I run python3 flocking.py, the memory usage increases 0.1% every second, is this expected behavior or something wrong with my setup?

Thank you for your work!

**Comment by matteobettini** [comment]
Uhh this is interesting, does it happen with all scenarios?

**Comment by matteobettini** [comment]
It seems to be related to rendering.

Can you try to run use_vmas_env without rendering and confirm that the issue does not occur?

**Comment by matteobettini** [comment]
Thank you so much for pointing this out.

I am investigating the issue.

You can track progress in #43

**Comment by matteobettini** [comment]
It seems to be related to rendering.

Can you confirm that you do not experience the issue in use_vmas_env when render=False?

**Comment by matteobettini** [comment]
Should be fixed, feel free to reopen the issue if it still occurs
