### ISSUE TITLE
Request: Any plans on create documentation in the future?

### ISSUE THREAD

**Issue by Zartris** [proroklab/VectorizedMultiAgentSimulator#45]
Hi 

I was reading through your code and examples, trying to figure out how things work.
I am having a hard time figuring out your units of variables and what they mean.
Example here is u_range, u_rot_range, max_speed. Are these upper limits for a single step, like acceleration or global max?
Are we using degrees or rads? m/s or pixel/step?

**Comment by matteobettini** [comment]
Hey,

Thanks so much for this.

Yeah I know, decs are needed and thy are planned, but I haven't found time to dedicate to that.

Regarding your questions:

- vmas is unitless, in the sense that we never explicit enforce a unit of measure, but you can interpret it values according to a unit. For example, when we deployed to the real world we used these units: all distances are meters, time is seconds, mass in kg, force actions are Newton, rotational actions are torque (N⋅m). So basically any value correstonds to the respective SI units
- the parameters with `x_range` define the max range for each dimension of a value, the parameters with `x_max` define a max norm for a value. These are constraints that last for all the sim (if you create an agent to have `v_max=3`, the maximum norm of the agent velocity will be enforced to follow this at each step). But of course you can change this param throughout the simulation if you want

**Comment by Zartris** [comment]
Thanks a lot for the quick answer. That is all I needed to hear.
