### ISSUE TITLE
[Feature] Allow any number of actions

### ISSUE THREAD

**Issue by Zartris** [proroklab/VectorizedMultiAgentSimulator#51]
Currently there is a limitation on the action input to be of size this function:
```
    def get_agent_action_size(self, agent: Agent):
        return (
            self.world.dim_p
            + (1 if agent.action.u_rot_range != 0 else 0)
            + (self.world.dim_c if not agent.silent else 0)
            if self.continuous_actions
            else 1
            + (1 if agent.action.u_rot_range != 0 else 0)
            + (1 if not agent.silent else 0)
        )
```
As this is what the simulator is expecting as an action.

However the process_action is a chance of shaping your networks output into the simulators input format.
My network could output positions and I could use process_action with a position controller to transform it into forces.
But as of right now we are checking and setting actions before this processing step.

Process_action:
https://github.com/proroklab/VectorizedMultiAgentSimulator/blob/fb2a8f73c36e549493c7ae799ac09b040495f1ee/vmas/simulator/environment/environment.py#L223

_set_action:
https://github.com/proroklab/VectorizedMultiAgentSimulator/blob/fb2a8f73c36e549493c7ae799ac09b040495f1ee/vmas/simulator/environment/environment.py#L220

The process_action expects an agent with the action set as u and u_rot, however we are checking u and u_rot before giving it to process_action. So an option is to do:
1. move the process_action above the _set_action function.
2. make process_action take in an agent and the action and have the it return the processed action
3. run the _set_action for sanity check 

If you are not sure what and why this, I can make a PR. 
Just tell me if you think it is something you interested in or if it is out of scope of the simulator.

**Comment by Zartris** [comment]
I agree that an input check is good to check. However, the available input format is just too specific for me as I do not want to develop a single-step model, and this is the only option this simulation gives.
I will develop this myself for the project, don't worry about it then.

**Comment by matteobettini** [comment]
Let me know what type pf flexibility you would like so i can add it to my next refactoring.

the things i have for now are.

- Allow any number of actions
- Allow to specify a custom range for each action

Are there any other features you would like?

**Comment by matteobettini** [comment]
Ok, i have already in mind how to do this

the idea is that the user will be able to choose the number of actions when creating an agent (default 2). 

If everything is left as default those 2 actions will be piped to the 2d forces. 

If the actions are set to 3, and all else is left default, those 3 will be piped to forces and torque

if user implements process_actions, the user will be responsible for piping the actions to forces and torque with a custom preprocessor. 
This will allow any number of actions, as long as the preprocessor fills at least the forces.

in any case, the simulator will still try to use the first 2 (3 if available) to fill forces (and  torque) in case this has not been done by a preprocessor.

in general, the direction of this change will be that u_rot will be removed. And there will be just a variable sized u completely decoupled from the physics, with some default physical interpretation easily customizable

**Comment by matteobettini** [comment]
I ll work on this as soon as i find time.
It is in my todos
