### ISSUE TITLE
Sim to real 

### ISSUE THREAD

**Issue by SHITIANYU-hue** [proroklab/VectorizedMultiAgentSimulator#56]
Hello, Thanks for sharing the code!

May I know if it supports deploying the multi-agent policy on real robot, such as turtle robot to conduct multi-robot collaboration. thanks!

**Comment by matteobettini** [comment]
Hello,

Yes this is definitely supported.

VMAS just offers the simulation framework, you can use any machine learning library to train your policy (PyTorch, tensorflow, Jax, ...).

We suggest using it with PyTorch and [TorcRL](https://pytorch.org/rl/).

I such case to deploy your trained model on rogots such as turtlebots you just need to save the model you trained and on the turtlebots have a python script call it with the observation and the model will give you the next action.

We have used vmas on the real robots here https://matteobettini.com/publication/heterogeneous-multi-robot-reinforcement-learning/ for example
