### ISSUE TITLE
"large" box and lines are heavy for collision computations 

### ISSUE THREAD

**Issue by Zartris** [proroklab/VectorizedMultiAgentSimulator#57]
Hi again

I want to enclose my environment so the small devil agents are not running away. However, the performance is halved just by adding four walls around the training area. 

```
    def collides(self, a: Entity, b: Entity) -> bool:
        if (not a.collides(b)) or (not b.collides(a)) or a is b:
            return False


        a_shape = a.shape
        b_shape = b.shape
        if (
                torch.linalg.vector_norm(a.state.pos - b.state.pos, dim=1)
                > a.shape.circumscribed_radius() + b.shape.circumscribed_radius()
        ).all():
            return False
        # Here we assume that if both entities are not movable and not rotatable, they cannot collide (user error)
        if not a.movable and not a.rotatable and not b.movable and not b.rotatable:
            return False
        if {a_shape.__class__, b_shape.__class__} in self._collidable_pairs:
            return True
        return False
```

The "problem" comes from the circumscribed_radius as for these "long" objects this value is very big and almost all agents are seen as colliding with the object.
So we are trying to compute the force with _get_collision_force between the large object and almost all other collidable objects.

Now the question is, can we do this smarter? There is a lot of collision detection method, but almost all of them requires another type of data structure and is hard to implement using the current architecture, and since this is Python, these will also not scale very well.

**Comment by matteobettini** [comment]
Have you tried to see scenarios where I implemented such boundaries?
You can do it by using world limits and just rendering the lines in extra_render.

See https://github.com/proroklab/VectorizedMultiAgentSimulator/blob/main/vmas/scenarios/passage.py or similar

**Comment by Zartris** [comment]
Ah, yea that seems to work for now.
Thanks
