### ISSUE TITLE
[Question] Creating environments with 100 agents takes an infinite amount of time

### ISSUE THREAD

**Issue by Filocava99** [proroklab/VectorizedMultiAgentSimulator#77]
Hi, I am having troubles instantiating environments with up to 100 agents: I debugged the code and it just waits foreverer for the class constructor to finish, meanwhile my computer resources were not busy at all, having CPU at 10% and GPU at 3%; the only exception was the ram that reached 20GB very quickly and then stopped, even tough I had 12GB left.
It doesn't seem to be a lack of computational power, and neither of memory, do you have any idea?

**Comment by matteobettini** [comment]
Hey, thanks for sharing this. 

Could you share a minimal scenario i can use to reproduce your case?

**Comment by Filocava99** [comment]
Hi, I implemented a cohesion and collision scenario using DQL, you can find the branch of the experiment [here](https://github.com/Filocava99/VMAS-DQL-playground/tree/cohesion-and-collision) :)

**Comment by matteobettini** [comment]
Ok so here are some issues with what you are trying to do:

1. you are telling vmas to find postions for 100 agents in the space [-1,1] which seems impossible. My bet is that the script is stuck here https://github.com/Filocava99/VMAS-DQL-playground/blob/44b5b8426c8c9a92a5a71805463215df8e653f3f/Cleaning.py#L79
2. You are equipping each agent with lidar. If you want to simulate > 100 agents, doing with each having a lidar seems like it would have scaling issues

The following simple scenario I created with 100 agents runs fine for me

```python
#  Copyright (c) 2022-2024.
#  ProrokLab (https://www.proroklab.org/)
#  All rights reserved.
from typing import Dict

import torch
from torch import Tensor

from vmas import render_interactively
from vmas.simulator.core import Agent, World, Landmark
from vmas.simulator.scenario import BaseScenario
from vmas.simulator.utils import Color, X, TorchUtils
from vmas.simulator.controllers.velocity_controller import VelocityController


class Scenario(BaseScenario):
    def make_world(self, batch_dim: int, device: torch.device, **kwargs):
        self.n_agents = kwargs.get("n_agents", 100)

        # Make world
        world = World(
            batch_dim,
            device,
        )
        for i in range(self.n_agents):
            agent = Agent(
                name=f"agent_{i}",
                collide=False,
            )
            world.add_agent(agent)

        return world

    def reset_world_at(self, env_index: int = None):
        pass

    def reward(self, agent: Agent):
        return torch.zeros(self.world.batch_dim, device=self.world.device)

    def observation(self, agent: Agent):
        return torch.cat(
            [agent.state.pos, agent.state.vel],
            dim=-1,
        )


if __name__ == "__main__":
    render_interactively(__file__, control_two_agents=True)

```

If I were you I would start from a simple scenario like this and add the complexity you need iteratively. This way you can notice what is the added feature that most impacts your performance

**Comment by Filocava99** [comment]
Thanks! Didn't think about the complexity of so many lidars. I'll find another way :)
