### ISSUE TITLE
Changing mass but no effect 

### ISSUE THREAD

**Issue by prinshul** [proroklab/VectorizedMultiAgentSimulator#84]
Hi

I am trying to change mass in balance
https://github.com/proroklab/VectorizedMultiAgentSimulator/blob/main/vmas/scenarios/balance.py
Line 17
self.package_mass = kwargs.get("package_mass", 5)
I changed to it 5000 but there was no effect on the performance. I think changing package mass should change episodic rewards as in the Readme it's mentioned that gravity and masses are customizable.

Is this the correct place or way to change mass. Similar observation is in reverse transport with mass.

**Comment by matteobettini** [comment]
If you are executing that file you need to change the mass here https://github.com/proroklab/VectorizedMultiAgentSimulator/blob/a883c90248f264136cc1840c911da96c87d5a4d7/vmas/scenarios/balance.py#L293

not its default value
